### PR TITLE
Feat: Inventory grid

### PR DESCRIPTION
**Pull request by PedroChaparro**
### Includes

- [x] Add "placeholder" images for the items and the Loomballs. 
- [x] Service to request the user items from the backend. 
- [x] Components to render the items. 
- [x] Loading skeletons.
- [x] Receive a callback to facilitate opening the modal (Not my task).    

### Preview

<table><tr><td>
    
</td><td>
    
</td></tr></table>

### CODE REVIEW

**Review by SilviaPabon — APPROVED** [review]
📱

**Review by Woynert — CHANGES_REQUESTED** [review]
I noticed there is a gap that cuts the content.

**Comment by Woynert** [comment]
Also it would be good if the Loomballs also got a description... But let's not focus on that for now.

**Comment by PedroChaparro** [comment]
> I noticed there is a gap that cuts the content.

Fixed. The origin of the gap was the `Container` component, so, the `padding` was replaced with `paddingHorizontal`.

**Review by Woynert — APPROVED** [review]
Good work!

**Pull request merged**
