### PR TITLE
Feat: Loomies details

### PR DESCRIPTION
**Pull request by PedroChaparro**
### Includes

- [x] Fix linter warnings. 
- [x] Page to show the details of some Loomie. 
- [x] Redirect to the details page when some Loomie is "clicked".
- [x] Increment the stats according to the Loomie level.
- [x] Render the Loomie model using Babylon **(Woynert)**.

#### Edit: Babylonjs changes

- Created Babylonjs provider which is now the place to manage the different scenes.
- Models are now preloaded/loaded per scene individually.
- Some Loomie models are not perfectly centered. This will be fixed in the PR for adding the textures.
- All meshes from the details page are deleted when exiting the page.

### Preview

|image|image|
|---|---|

### CODE REVIEW

**Comment by PedroChaparro** [comment]
@Woynert help 🏳️. 

1.  I have a REALLY BIG performance issue. The first time I navigate to the details page I get around 50 FPS, but as I go back and re-enter the details page multiple times the FPS drops drastically to 1-5 FPS.

2. The first time you generate the map view, if you go to any Loomie's details page fast enough, the wild Loomies and gyms will appear in the scene:

image

3. I also notice that some Loomies are shorter than others, I tried to lock the camera to a middle point for all the Loomies but maybe it isn´t the best solution.

**Comment by Woynert** [comment]
Thanks for listing the issues, I'll get to it over the weekend.

**Comment by PedroChaparro** [comment]
@Woynert pull before starting your work to avoid merge conflicts.

**Review by SilviaPabon — APPROVED** [review]
👏🏻!!

**Review by andres123dbh — APPROVED** [review]

**Pull request merged**
